name: Remio
markdown: redcarpet
highlighter: pygments
permalink: none

destination: build
exclude: [sass, gulp, node_modules, remio.sublime-project, README.md, gulpfile.js]

url: http://www.kapuhonu.com